### ISSUE TITLE
"Cannot convert data to toml"

### ISSUE THREAD

**Issue by lukego** [cargo2nix/cargo2nix#149] opened 2020-11-23 14:31 UTC
Hello! I'm using cargo2nix for the first time - and indeed compiling a Rust program for the first time - and it's starting off great but I'm hitting some errors like this:

```
unpacking sources
unpacking source archive /nix/store/43ksm0c42cmsy0am22vv2nm4rkqwbddx-byteorder-1.3.4.tar.gz
source root is byteorder-1.3.4
setting SOURCE_DATE_EPOCH to timestamp 1581081480 of file byteorder-1.3.4/Cargo.toml
patching sources
configuring
building
Error: Cannot convert data to TOML (Invalid type <class 'NoneType'>)
```

and I'm wondering if someone could suggest a way to troubleshoot this?

Background links:

- Rust repo that I'm trying to build: https://github.com/feenkcom/libskia
- [Gist](https://gist.github.com/099c3b68fa27271fa1e7f1a206df035e) containing `Cargo.lock`, `Cargo.nix`, `default.nix`.
- [Gisted Cargo.toml](https://gist.github.com/lukego/d3bf4990cb1571e8f9bc7b7779438d7a) referenced in the error above.
- Installed `cargo2nix` today according to the README on a recent NixOS master host.

Thanks for any pointers!

**Comment by lukego** [comment] 2020-11-24 08:07
Notes:

Linting the `Cargo.toml` gisted above yielded success so the data seems to be superficially OK.


Installing the `update-cargo` branch (#111) gets an error when running the `cargo2nix` step:

```
$ nix-env -iA package -f https://github.com/cargo2nix/cargo2nix/tarball/update-cargo
...
$ cargo2nix -s | tee Cargo.nix 
error: could not execute process `rustc -vV` (never executed): No such file or directory (os error 2)
```

**Comment by lukego** [comment] 2020-11-24 08:42
I've used `nix-build -K` to inspect the failed result and narrowed it down to this command:

```
remarshal -if toml -of json Cargo.original.toml \
  | jq "{ package: .package , lib: .lib , bin: .bin , test: .test , example: .example , bench: (if \"$registry\" == \"unknown\" then .bench else null end) } + $manifestPatch" \
  | remarshal -if json -of toml > Cargo.toml
Error: Cannot convert data to TOML (Invalid type <class 'NoneType'>)
```

I've also confirmed that there is no error if the `jq` is removed from the pipeline so I suppose that somehow it is introducing some JSON that can't be converted into TOML at the end.

**Comment by lukego** [comment] 2020-11-24 09:48
I can also dump the JSON that is failing to convert to TOML:

```json
[luke@snowy:/tmp/nix-build-crate-byteorder-1.3.4.drv-0/byteorder-1.3.4]$ remarshal -if toml -of json Cargo.original.toml   | jq "{ package: .package , lib: .lib , bin: .bin , example: .example , bench: (if \"$registry\" == \"unknown\" then .bench else null end) } + $manifestPatch" 
{
  "package": {
    "authors": [
      "Andrew Gallant <jamslam@gmail.com>"
    ],
    "build": "build.rs",
    "categories": [
      "encoding",
      "parsing"
    ],
    "description": "Library for reading/writing numbers in big-endian and little-endian.",
    "documentation": "https://docs.rs/byteorder",
    "exclude": [
      "/ci/*"
    ],
    "homepage": "https://github.com/BurntSushi/byteorder",
    "keywords": [
      "byte",
      "endian",
      "big-endian",
      "little-endian",
      "binary"
    ],
    "license": "Unlicense OR MIT",
    "name": "byteorder",
    "readme": "README.md",
    "repository": "https://github.com/BurntSushi/byteorder",
    "version": "1.3.4"
  },
  "lib": {
    "bench": false,
    "name": "byteorder"
  },
  "bin": null,
  "example": null,
  "bench": null,
  "features": {
    "default": [],
    "std": []
  },
  "profile": {
    "release": {
      "opt-level": 3
    }
  }
}
```

Is the problem the `null` fields? Is this really an issue for `nixos/nixpkgs`?

**Comment by lukego** [comment] 2020-11-24 13:24
I see the issue seems to be in cargo2nix `overlay/mkcreate.nix` function `overrideCargoManifest`: https://github.com/cargo2nix/cargo2nix/blob/master/overlay/mkcrate.nix#L161

**Comment by psionic-k** [comment] 2020-12-09 17:09
I will look into this.  I believe you're on the right path though looking into the use of remarshall and jq

Heads up, you have a lot of sys crates in your deps that will likely require some native deps overrides in overlay/overrides.nix or provided as extra overrides to `makePackageSet'`

**Comment by tim2CF** [comment] 2020-12-10 16:18
I have similar issue. Upgraded nixpkgs to latest and now getting
`Error: Cannot convert data to TOML (Invalid type <class 'NoneType'>)`

**Comment by nightmared** [comment] 2020-12-23 11:11
Hey, I ran into the same issue, so I guess the library switch in remarshal is the reason for this (I think they traded parsers in 0.14, the version that is currently provided in nixpkgs-unstable, and nixpkgs-20.09 still uses remarshal 0.10 - thus running the old parser).
I have below a small patch that can make cargo2nix work in the meantime by using https://github.com/sclevine/yj instead of remarshal. Not sure if I should open a PR or if the ideal way would be to fix the library that remarshal switched to (https://github.com/sdispater/tomlkit/) ?
```
From 7833fe5b39706ac6f9d71f1ac6ef213c67d48dd1 Mon Sep 17 00:00:00 2001
From: Simon THOBY <git@nightmared.fr>
Date: Wed, 23 Dec 2020 12:03:36 +0100
Subject: [PATCH] switch from remarshal to yt (remarshal cannot parse some
 creates toml files)

---
 overlay/lib/fetch.nix |  6 +++---
 overlay/mkcrate.nix   | 16 +++++++++-------
 2 files changed, 12 insertions(+), 10 deletions(-)

diff --git a/overlay/lib/fetch.nix b/overlay/lib/fetch.nix
index 602699d..ff6aa1a 100644
--- a/overlay/lib/fetch.nix
+++ b/overlay/lib/fetch.nix
@@ -8,18 +8,18 @@ rec {

   fetchCrateGit = { url, name, version, rev }:
     let
-      inherit (buildPackages) runCommand jq remarshal;
+      inherit (buildPackages) runCommand jq yj;
       repo = builtins.fetchGit {
         name = "${name}-${version}-src";
         inherit url rev;
       };
     in
       /. + builtins.readFile (runCommand "find-crate-${name}-${version}"
-        { nativeBuildInputs = [ jq remarshal ]; }
+        { nativeBuildInputs = [ jq yj ]; }
         ''
           shopt -s globstar
           for f in ${repo}/**/Cargo.toml; do
-            if [[ "$(remarshal -if toml -of json "$f" | jq '.package.name == "${name}" and .package.version == "${version}"')" == "true" ]]; then
+            if [[ "$(yj -t < "$f" | jq '.package.name == "${name}" and .package.version == "${version}"')" == "true" ]]; then
               echo -n "''${f%/*}" > $out
               exit 0
             fi
diff --git a/overlay/mkcrate.nix b/overlay/mkcrate.nix
index d4022d9..fa79e95 100644
--- a/overlay/mkcrate.nix
+++ b/overlay/mkcrate.nix
@@ -102,8 +102,8 @@ let
     nativeBuildInputs = [ cargo ] ++ buildtimeDependencies;

     depsBuildBuild =
-      let inherit (buildPackages.buildPackages) stdenv jq remarshal;
-      in [ stdenv.cc jq remarshal ];
+      let inherit (buildPackages.buildPackages) stdenv jq yj;
+      in [ stdenv.cc jq yj ];

     # Running the default `strip -S` command on Darwin corrupts the
     # .rlib files in "lib/".
@@ -167,7 +167,8 @@ let
         echo source = \"registry+''${registry}\" >> Cargo.lock
       fi
       mv Cargo.toml Cargo.original.toml
-      remarshal -if toml -of json Cargo.original.toml \
+
+      yj -t < Cargo.original.toml \
         | jq "{ package: .package
               , lib: .lib
               , bin: .bin
@@ -175,7 +176,8 @@ let
               , example: .example
               , bench: (if \"$registry\" == \"unknown\" then .bench else null end)
               } + $manifestPatch" \
-        | remarshal -if json -of toml > Cargo.toml
+        | jq '. | walk(if type == "object" then with_entries(select(.value != null)) else . end)' \
+        | yj -jt > Cargo.toml
     '';

     setBuildEnv = ''
@@ -183,13 +185,13 @@ let

       if (( MINOR_RUSTC_VERSION < 41 )); then
         isProcMacro="$(
-          remarshal -if toml -of json Cargo.original.toml \
+          yj -t < Cargo.original.toml \
           | jq -r 'if .lib."proc-macro" or .lib."proc_macro" then "1" else "" end' \
         )"
       fi

       crateName="$(
-        remarshal -if toml -of json Cargo.original.toml \
+        yj -t < Cargo.original.toml \
         | jq -r 'if .lib."name" then .lib."name" else "${replaceChars ["-"] ["_"] name}" end' \
       )"

@@ -247,7 +249,7 @@ let

     installPhase = ''
       mkdir -p $out/lib
-      cargo_links="$(remarshal -if toml -of json Cargo.original.toml | jq -r '.package.links | select(. != null)')"
+      cargo_links="$(yj -t < Cargo.original.toml | jq -r '.package.links | select(. != null)')"
       if (( MINOR_RUSTC_VERSION < 41 )); then
         install_crate ${host-triple} ${if release then "release" else "debug"}
       else
--
2.29.2
```

**Comment by psionic-k** [comment] 2020-12-23 15:58
PR please.  There's pretty good coverage if it passes CI

**Comment by psionic-k** [comment] 2021-01-09 13:40
I will try to reproduce the parse issue.  At second glance, we're probably shooting ourselves in the foot with that jq query writing something that `remarshal` can't convert, and I have a strong suspicion about the handling of bench, which is not the primary role of `cargo2nix`

For now, I prefer any solution that involves munging the output  from `remarshal` and or `jq` output so that our use of `jq` and `remarshal` form a consistent ring.

I think long term, the tomls might be known beforehand from cargo metadata, pushing as much work up to the `cargo2nix -f` and eliminating this style of passing information up to dependents or getting information from the crate as it's being built

**Comment by psionic-k** [comment] 2021-01-09 14:05
I wrote a PR.  I think the version of `nixpkgs` may be at fault, but we can remove the nulls for more consistent behavior.

I could not reproduce with my version of nixpkgs using the offending toml:

```
[nix-shell:~/Desktop/testshit]$ remarshal -if toml -of json Cargo.original.toml   | jq "{ package: .package , lib: .lib , bin: .bin , example: .example , bench: (if \"$registry\" == \"unknown\" then .bench else null end) } | with_entries( select( .value != null ) )"  | remarshal -if json -of toml > Cargo.toml

[nix-shell:~/Desktop/testshit]$ remarshal -if toml -of json Cargo.original.toml   | jq "{ package: .package , lib: .lib , bin: .bin , example: .example , bench: (if \"$registry\" == \"unknown\" then .bench else null end) }"  | remarshal -if json -of toml > Cargo.toml
```

The only thing left then is the mystery value inside `$manifestPatch`

Let me know if this branch fixes things up and I'll go ahead and bump the minor version and merge it!

**Comment by psionic-k** [comment] 2021-01-09 14:08
We're going to fix this by changing the output to something that can be remarshalled more consistently, either by modified `jq` query or by munging with `sed` etc

**Comment by psionic-k** [comment] 2021-01-11 11:07
```toml
[package]
name = "ansi_term"
version = "0.11.0"
authors = ["ogham@bsago.me", "Ryan Scheel (Havvy) <ryan.havvy@gmail.com>", "Josh Triplett <josh@joshtriplett.org>"]
description = "Library for ANSI terminal colours and styles (bold, underline)"
homepage = "https://github.com/ogham/rust-ansi-term"
documentation = "https://docs.rs/ansi_term"
readme = "README.md"
license = "MIT"

[lib]
name = "ansi_term"

[target."cfg(target_os=\"windows\")".dependencies.winapi]
version = "0.3.4"

features = ["errhandlingapi", "consoleapi", "processenv"]
```

This toml breaks the same way as this issue and also another way.

Replacing the escaped quotes in the `target` key with single quotes resulted in what looks like a good toml and a successful build by cargo.

Because TOML doesn't like line breaks in table names, a hacked (non-parser) solution should be fine.  I'm pursuing that route.

**Comment by psionic-k** [comment] 2021-01-11 14:46
```
      # Remarshal version cannot handle escaped double quotes in table key paths
      while grep '\[[^"]*"[^\\"]*\\"[^\\"]*\\"[^"]*[^]]*\]' Cargo.original.toml; do
        sed -i -r 's/\[([^"]*)"([^\\"]*)\\"([^\\"]*)\\"([^"]*)"([^]]*)\]/[\1"\2'"'"'\3'"'"'\4"\5]/g' Cargo.original.toml
      done;
      remarshal -if toml -of json Cargo.original.toml \
        | jq "{ package: .package
              , lib: .lib
              , bin: .bin
              , test: .test
              , example: .example
              , bench: (if \"$registry\" == \"unknown\" then .bench else null end)
              } | with_entries(select( .value != null ))
              + $manifestPatch" \
        | jq "del(.[][] | nulls)" \
        | remarshal -if json -of toml > Cargo.toml
```
Here's a preview.  Converts escaped quote strings to single quotes inside quoted string.  Removes null and null value keys.   Somehow I picked a crate that had every single issue.

**Comment by psionic-k** [comment] 2021-01-11 16:31
@nightmared  @lukego  I pushed the changes to the PR branch.   The `static-web-server` crate depended on a lot of tomls that had issues.  I think this solution will work for your cases and will be strong enough until a better path is ready.

**Comment by cryptoquick** [comment] 2021-01-11 17:06
@psionic-k I just ran:

```sh
nix-env -iA package -f https://github.com/positron-solutions/cargo2nix/tarball/dont-output-nulls-from-jq
cargo2nix -f
nix-build
```

It did result in a different Cargo.nix, but got plenty of issues in the following crates:

```
unpacking sources
unpacking source archive /nix/store/0k5vj5wfwqi24xdi7wfz465lyj2fbkrl-anyhow-1.0.37.tar.gz
source root is anyhow-1.0.37
patching sources
configuring
building
Error: Cannot convert data to TOML (Invalid type <class 'NoneType'>)
unpacking sources
unpacking source archive /nix/store/id1cvxz5cqy128b5sg08r427smp1pqj7-infer-0.3.4.tar.gz
source root is infer-0.3.4
setting SOURCE_DATE_EPOCH to timestamp 1609615034 of file infer-0.3.4/Cargo.toml
patching sources
configuring
building
Error: Cannot convert data to TOML (Invalid type <class 'NoneType'>)
unpacking sources
unpacking source archive /nix/store/lkkxnbx2ajlh5279pip1w894glgn8nsc-byteorder-1.4.2.tar.gz
source root is byteorder-1.4.2
patching sources
configuring
building
Error: Cannot convert data to TOML (Invalid type <class 'NoneType'>)
unpacking sources
unpacking source archive /nix/store/s1mzmjannmqfmj5y9wkcmvxjyhnzv3gy-cfg-if-0.1.10.tar.gz
source root is cfg-if-0.1.10
setting SOURCE_DATE_EPOCH to timestamp 1569338828 of file cfg-if-0.1.10/Cargo.toml.orig
patching sources
configuring
building
Error: Cannot convert data to TOML (Invalid type <class 'NoneType'>)
unpacking sources
unpacking source archive /nix/store/clksqpbv8p9agvaliazdwxyiivnpk7mi-cfg-if-1.0.0.tar.gz
source root is cfg-if-1.0.0
setting SOURCE_DATE_EPOCH to timestamp 1602009852 of file cfg-if-1.0.0/Cargo.toml
patching sources
configuring
building
Error: Cannot convert data to TOML (Invalid type <class 'NoneType'>)
unpacking sources
unpacking source archive /nix/store/w166cygrmgvvrdgc9wi0n2b3bp2d0kw7-color_quant-1.1.0.tar.gz
source root is color_quant-1.1.0
setting SOURCE_DATE_EPOCH to timestamp 1602271036 of file color_quant-1.1.0/Cargo.toml
patching sources
configuring
building
Error: Cannot convert data to TOML (Invalid type <class 'NoneType'>)
unpacking sources
unpacking source archive /nix/store/cb4ysjar271iprx8ygzvq9l76r6f4p2d-fnv-1.0.7.tar.gz
source root is fnv-1.0.7
setting SOURCE_DATE_EPOCH to timestamp 1589472388 of file fnv-1.0.7/Cargo.toml
patching sources
configuring
building
Error: Cannot convert data to TOML (Invalid type <class 'NoneType'>)
unpacking sources
unpacking source archive /nix/store/a1dmjwzz5g5b37axihrrl1nldvhaw4k7-futures-core-0.3.9.tar.gz
source root is futures-core-0.3.9
patching sources
configuring
building
Error: Cannot convert data to TOML (Invalid type <class 'NoneType'>)
unpacking sources
unpacking source archive /nix/store/qqqhgg4vljgmd7gjaa7wvjfyrrd1f7kb-futures-io-0.3.9.tar.gz
source root is futures-io-0.3.9
patching sources
configuring
building
Error: Cannot convert data to TOML (Invalid type <class 'NoneType'>)
unpacking sources
unpacking source archive /nix/store/kzm9dfmnzbfx9kni5bwnchfdivbwsrk9-iced_core-0.3.0.tar.gz
source root is iced_core-0.3.0
setting SOURCE_DATE_EPOCH to timestamp 1606405746 of file iced_core-0.3.0/Cargo.toml
patching sources
configuring
building
Error: Cannot convert data to TOML (Invalid type <class 'NoneType'>)
unpacking sources
unpacking source archive /nix/store/884mj3nwpfiywsbh9fl4abxz92w8qbd2-itoa-0.4.7.tar.gz
source root is itoa-0.4.7
patching sources
configuring
building
Error: Cannot convert data to TOML (Invalid type <class 'NoneType'>)
unpacking sources
unpacking source archive /nix/store/dggvfpb5fsrk53m31hvv4wv27zj08zj5-libc-0.2.82.tar.gz
source root is libc-0.2.82
patching sources
configuring
building
Error: Cannot convert data to TOML (Invalid type <class 'NoneType'>)
```

**Comment by psionic-k** [comment] 2021-01-12 08:43
@cryptoquick  I would check your overlay being imported in your `default.nix` for this project.  Updating the `Cargo.nix` will only provide the dependency and feature information.  The overlay is the other half.  You want it to be updated to pin to `a47a344b865c399a773e257e1ef1fc052c27ee86`

**Comment by psionic-k** [comment] 2021-01-12 08:50
To anyone following along, the PR affects the overlay, which is usually applied to your `pkgs` in `default.nix`.  With niv it looks something like:

```nix
{
  sources ? import ./nix/sources.nix,   # these are niv pins
  system ? builtins.currentSystem,
  crossSystem ? null,
}:
let
  rustChannel = "1.49.0";

  # the cargo2nix version from sources is providing the overlay that consumes your Cargo.nix packageFun
  inherit (sources) nixpkgs nixpkgs-mozilla cargo2nix; 
  pkgs = import nixpkgs {
    inherit system crossSystem;
    overlays =
      let
        rustOverlay = import "${nixpkgs-mozilla}/rust-overlay.nix";
        cargo2nixOverlay = import "${cargo2nix}/overlay";
      in
        [ cargo2nixOverlay rustOverlay ];
  };

  rustPkgs = pkgs.rustBuilder.makePackageSet' {
    inherit rustChannel;
    packageFun = import ./Cargo.nix;
    workspaceSrc = sources.some-rust-project;
  };
in rec {
  inherit rustPkgs;

  ci = with builtins; map
    (crate: pkgs.rustBuilder.runTests crate { })
    (attrValues rustPkgs.workspace);

  package = rustPkgs.workspace.some-rust-project {};

  shell = pkgs.mkShell {
    inputsFrom = pkgs.lib.mapAttrsToList (_: crate: crate {}) rustPkgs.noBuild.workspace;
    nativeBuildInputs = with rustPkgs; [ cargo rustc rust-src ] ++ [ (import cargo2nix {}).package ];

    RUST_SRC_PATH = "${rustPkgs.rust-src}/lib/rustlib/src/rust/library";
  };
}
```

See the default.nix of cargo2nix itself for an example with ad-hoc `fetchTarball` pins

**Comment by psionic-k** [comment] 2021-01-15 12:26
Can anyone with a breakage case update their overlay and give some results?  I was able to see lots of broken cases in `static-web-server` that were fixed by #171   I want to corroborate a fix before closing this issue.

**Comment by nightmared** [comment] 2021-01-15 17:57
All right, I finally committed myself to trying it again, and it does work for my use case (a small project but with quite a few deps - tokio, clap, chrono, futures, rayon, rust-s3, webpki, hyper, serde, …), so it's definitely better than before ! (I can't say more than that because maybe it would have failed in a similar fashion, had I used a specific dependency)
Congrats, your patch works !

**Comment by cryptoquick** [comment] 2021-01-15 19:55
I can also confirm, this fixes my issue, after putting:

```nix
  cargo2nix ? builtins.fetchGit {
    url = https://github.com/positron-solutions/cargo2nix;
    ref = "dont-output-nulls-from-jq";
    rev = "a47a344b865c399a773e257e1ef1fc052c27ee86";
  }
```

Thanks for this!

**Comment by psionic-k** [comment] 2021-01-17 10:33
:1st_place_medal:   Thanks a ton!  I'm going to merge #171 and let this issue close.  Hope it stays that way until the implementation for #158 can be ready :crossed_fingers:

**Closed** 2021-01-18 05:37 UTC
Labels: bug
