### ISSUE TITLE
Investigate import-from-derivation pattern

### ISSUE THREAD

**Issue by ebkalderon** [cargo2nix/cargo2nix#87] opened 2020-02-28 06:51 UTC
A common pattern used by several `foo2nix` tools is the [import-from-derivation](https://nixos.wiki/wiki/Import_From_Derivation) pattern.

In this pattern, users do not call `cargo2nix -f` directly and check in the resulting `Cargo.nix` into source control. Instead, a function inside the `default.nix` takes the top-level `Cargo.toml` and `Cargo.lock` as input and runs `cargo2nix -f` inside of a Nix derivation, vendoring the generated `Cargo.nix` into the Nix store. As long as the input `Cargo.toml` and `Cargo.lock` do not change, the command is not executed again.

**Comment by ebkalderon** [comment] 2020-02-28 06:57
Some benefits of using this pattern:

* Improved usability
  * No need for users to install a separate tool to use `cargo2nix`.
  * Synchronization of the `Cargo.lock` and `Cargo.nix` is fully automated by Nix.
  * Users work with the `Cargo.toml` and `Cargo.lock` like it was a normal Cargo project.
* Version compatibility improvements
  * No need to worry about version checking between the Nixpkgs overlay and CLI tool because the tool can be distributed as part of the overlay.
  * Developers are guaranteed to be using the same version of `cargo2nix` per Cargo project.
* Less diff noise in source control
  * Since the `Cargo.nix` is never checked into source control, changes to it do not pollute line diffs during code review.

Some drawbacks of using this pattern:

* Unclear if `cargo::ops::resolve_ws_with_opts()` will work inside a sandboxed Nix derivation
  * This is because it may attempt to access the Internet to update the `crates.io-index` or attempt to read the `~/.cargo` directory.
  * Will need to investigate this further.
* Projects using different versions of the Nix overlay can't easily share the same `cargo2nix` binary
  * Repositories using different versions of the `cargo2nix` overlay in their `default.nix` may not be able to share the same `cargo2nix` binary, even if there are no functional differences between them, because their Git revisions do not match. Currently, the `cargo2nix` binary is installed with `nix-env` separately from the Nix overlay, meaning that an upgrade to the overlay version cannot cause the binary to recompile.
  * The `cargo2nix` binary is pretty heavy since it statically links against `cargo` as a library, which means the uncached initial compilation would be slow.

**Comment by ebkalderon** [comment] 2020-03-17 19:17
There exists a nightly Cargo feature called `no-index-update` which would allow for lockfiles to be generated and resolved without reaching for the network and without attempting to update the local index, which I imagine would be promising for us: https://github.com/rust-lang/cargo/issues/7404

**Comment by antigravityla** [comment] 2020-05-27 02:51
https://github.com/rust-lang/cargo/pull/4990

Part of this looks done.  In any case, it's always easier to force the impurities out through use :smiling_imp: 

>  Instead, a function inside the default.nix takes the top-level Cargo.toml and Cargo.lock as input and runs cargo2nix -f inside of a Nix derivation

Sounds like two totally different API's / use patterns, so also no backwards compatibility issues.

> This is because it may attempt to access the Internet to update the crates.io-index or attempt to read the ~/.cargo directory.

In terms of repeatability, the lock is probably the right layer to nixify.  In terms of sandbox, generating the lock and the Cargo.nix could be treated like a fetcher.  Treat the lockfile generation as a fetch and the toml path as the input with a sha on the lock output for the reproducibility.  Instead of fetching source, fetching info about deps.

> Projects using different versions of the Nix overlay can't easily share the same cargo2nix binary 

Given the extremely low guarantees of consistent behavior across cargo2nix binaries due to cargo changes, there's no layer to normalize, and it's reasonable to tie overlay pins to cargo2nix pins and not mix & match.

As always, bootstrapping is weird.  At least Cargo.nix is self hosting and the moz overlay can yield a working cargo, but it's not clear that all of these things will "just work" inside an `import-from-derivation` style treatment.

Are there any clear increments that can be done already?

**Comment by antigravityla** [comment] 2020-06-01 12:41
@trha recording output of a conversation with @ebkalderon.  Suggest implementing both target dependent features & import-from-derivation together.  If we get lucky and cargo2nix can be made to generate the correct Cargo.nix for a source with acceptable purity, we can through knowing the currently evaluated target select the correct target for cargo2nix and avoid having a cargo2nix per possible target.

**Comment by pikajude** [comment] 2020-07-14 15:36
One more design concern here: The build closure for `cargo2nix` itself involves C compiler, rustc, cargo, git, and so on and so forth. On Hydra, for example, the evaluator concurrency is configured separately from the builders, so if you happen to check in a job that uses cargo2nix or any other tool that generates a build plan at eval time, it may need to build a few dozen relatively expensive packages.

Note that this is also a problem for cabal2nix. I just thought it was worth mentioning here.

**Comment by ebkalderon** [comment] 2020-07-16 11:20
@pikajude Makes sense! Ideally, we'd also expose the option to specify a vendored version of the `Cargo.nix` to avoid the cost and/or unpredictability of generating at evaluation time, taking a page out of `yarn2nix`'s book.

**Comment by ollie-etl** [comment] 2021-04-12 17:21
I had a very crude go at this for local use:

```
  nixified-lockfile = with pkgs;
    stdenv.mkDerivation {
      name = "Cargo.nix";
      __noChroot = true;
      src = gitignoreSource ./.;
      nativeBuildInputs = [ cargo2nix rustc ];
      buildPhase = ''
        export HOME=$(pwd)
        cargo2nix -f
      '';
      installPhase = ''
        mkdir -p $out
        mv Cargo.nix $out/
      '';
    };
```

The evaluation time is _long_. At a guess, network access from inside nix is very slow, although I can't think why that'd be.

**Comment by psionic-k** [comment] 2022-05-14 16:44
Because nix itself seems to be slowly getting rid of all IFD, going to close this.  We can't generate the nix when evaluating the nix or it's very, very IFD.

**Closed by psionic-k** 2022-05-14 16:44 UTC
Labels: enhancement
